/* Generated By:JavaCC: Do not edit this line. CompiladorSlothConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorSlothConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETRA = 5;
  /** RegularExpression Id. */
  int DIGITO = 6;
  /** RegularExpression Id. */
  int CARACTERE = 7;
  /** RegularExpression Id. */
  int ASC = 8;
  /** RegularExpression Id. */
  int TIPOINT = 9;
  /** RegularExpression Id. */
  int TIPODOUBLE = 10;
  /** RegularExpression Id. */
  int TIPOCHAR = 11;
  /** RegularExpression Id. */
  int TIPOSTRING = 12;
  /** RegularExpression Id. */
  int TIPOBOOLEAN = 13;
  /** RegularExpression Id. */
  int TIPOVOID = 14;
  /** RegularExpression Id. */
  int RETORNO = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int ENDL = 18;
  /** RegularExpression Id. */
  int EOL = 19;
  /** RegularExpression Id. */
  int ABREVET = 20;
  /** RegularExpression Id. */
  int FECHAVET = 21;
  /** RegularExpression Id. */
  int ADD = 22;
  /** RegularExpression Id. */
  int SUB = 23;
  /** RegularExpression Id. */
  int MULT = 24;
  /** RegularExpression Id. */
  int MOD = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int POW = 27;
  /** RegularExpression Id. */
  int PORCE = 28;
  /** RegularExpression Id. */
  int ABREPAR = 29;
  /** RegularExpression Id. */
  int FECHAPAR = 30;
  /** RegularExpression Id. */
  int PONTO = 31;
  /** RegularExpression Id. */
  int IGUAL = 32;
  /** RegularExpression Id. */
  int DIF = 33;
  /** RegularExpression Id. */
  int MAIOR = 34;
  /** RegularExpression Id. */
  int MENOR = 35;
  /** RegularExpression Id. */
  int MAIGUAL = 36;
  /** RegularExpression Id. */
  int MEIGUAL = 37;
  /** RegularExpression Id. */
  int IGUALDADE = 38;
  /** RegularExpression Id. */
  int AND = 39;
  /** RegularExpression Id. */
  int OR = 40;
  /** RegularExpression Id. */
  int NOT = 41;
  /** RegularExpression Id. */
  int XOR = 42;
  /** RegularExpression Id. */
  int IF = 43;
  /** RegularExpression Id. */
  int ELSE = 44;
  /** RegularExpression Id. */
  int FOR = 45;
  /** RegularExpression Id. */
  int SEPFOR = 46;
  /** RegularExpression Id. */
  int WHILE = 47;
  /** RegularExpression Id. */
  int FOREACH = 48;
  /** RegularExpression Id. */
  int FIRST = 49;
  /** RegularExpression Id. */
  int LAST = 50;
  /** RegularExpression Id. */
  int BEGIN = 51;
  /** RegularExpression Id. */
  int END = 52;
  /** RegularExpression Id. */
  int IMPORT = 53;
  /** RegularExpression Id. */
  int GET = 54;
  /** RegularExpression Id. */
  int WRITE = 55;
  /** RegularExpression Id. */
  int COMENT = 56;
  /** RegularExpression Id. */
  int SEPFUN = 57;
  /** RegularExpression Id. */
  int NOMEVAR = 58;
  /** RegularExpression Id. */
  int STRING = 59;
  /** RegularExpression Id. */
  int INTEIRO = 60;
  /** RegularExpression Id. */
  int CARACTER = 61;
  /** RegularExpression Id. */
  int REAL = 62;
  /** RegularExpression Id. */
  int PORCENTAGEM = 63;
  /** RegularExpression Id. */
  int UNKNOWMTOKEN = 64;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<LETRA>",
    "<DIGITO>",
    "<CARACTERE>",
    "<ASC>",
    "\"int\"",
    "\"double\"",
    "\"char\"",
    "\"string\"",
    "\"boolean\"",
    "\"void\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"\\\\n\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"//\"",
    "\"/\"",
    "\"^\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"==\"",
    "\"=!\"",
    "\">\"",
    "\"<\"",
    "\"=>\"",
    "\"=<\"",
    "\"=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"|+\"",
    "\"when\"",
    "\"otherwise\"",
    "\"for\"",
    "\":\"",
    "\"while\"",
    "\"foreach\"",
    "\"first\"",
    "\"last\"",
    "\"begin\"",
    "\"end\"",
    "\"import\"",
    "\"get\"",
    "\"write\"",
    "<COMENT>",
    "\",\"",
    "<NOMEVAR>",
    "<STRING>",
    "<INTEIRO>",
    "<CARACTER>",
    "<REAL>",
    "<PORCENTAGEM>",
    "<UNKNOWMTOKEN>",
  };

}
